# Generated by Django 5.0.1 on 2024-01-10 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcrm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='ciry',
            new_name='city',
        ),
    ]
